language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then pip install http://lxml.de/files/lxml-3.3.1pre.tar.gz; fi'
  - python setup.py install
  - pip install nose coverage coveralls
# command to run tests
script: coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
